### PR TITLE
Added continuous integration configuration with JS linter

### PR DESCRIPTION
**Pull request by astrofrog**
I thought it might be useful to add a continuous integration job which automatically runs ``jshint`` to check for any potential issues - as I mentioned in my email it seems that if I try and run this inside the Python Qt WebEngine framework, some things identified as warnings by jshint are errors in Qt, e.g.:

```
Uncaught SyntaxError: Unexpected token ) (level=2, line_number=38, source_id=https://aperiosoftware.github.io/timeseries.js/resources/timeseries.js)
```

(This PR is still a work in progress)

### CODE REVIEW

**Comment by astrofrog** [comment]
Ok the CircleCI job is working and I filtered out the semicolon warnings. I still get a number of warnings:

```
resources/timeseries.js: line 38, col 190, Unexpected ')'.
resources/timeseries.js: line 38, col 190, Expected an identifier and instead saw ')'.
resources/timeseries.js: line 38, col 192, Expected ')' and instead saw ';'.
resources/timeseries.js: line 136, col 44, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (_obj, checkAndGo, files)
resources/timeseries.js: line 15, col 18, Weird construction. Is 'new' necessary?
resources/timeseries.js: line 169, col 5, Missing '()' invoking a constructor.
resources/timeseries.js: line 281, col 151, Unexpected ')'.
resources/timeseries.js: line 281, col 151, Expected an identifier and instead saw ')'.
resources/timeseries.js: line 281, col 153, Expected ')' and instead saw ';'.
resources/timeseries.js: line 333, col 17, 'i' is already defined.
resources/timeseries.js: line 445, col 10, Unnecessary semicolon.
resources/timeseries.js: line 477, col 17, 'i' is already defined.
resources/timeseries.js: line 501, col 46, eval can be harmful.
resources/timeseries.js: line 581, col 59, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (updateProperties)
resources/timeseries.js: line 582, col 61, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (updateProperties)
resources/timeseries.js: line 583, col 59, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (updateProperties)
resources/timeseries.js: line 617, col 57, The array literal notation [] is preferable.
resources/timeseries.js: line 631, col 57, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (g, i, j)
resources/timeseries.js: line 738, col 18, 'txt' used out of scope.
resources/timeseries.js: line 820, col 52, Expected a conditional expression and instead saw an assignment.
resources/timeseries.js: line 853, col 32, The array literal notation [] is preferable.
resources/timeseries.js: line 854, col 32, The array literal notation [] is preferable.
resources/timeseries.js: line 855, col 13, 'header' is already defined.
resources/timeseries.js: line 855, col 31, The array literal notation [] is preferable.
resources/timeseries.js: line 870, col 21, 'j' is already defined.
resources/timeseries.js: line 881, col 99, Unnecessary semicolon.
resources/timeseries.js: line 920, col 16, eval can be harmful.
resources/timeseries.js: line 984, col 24, You might be leaking a variable (rem) here.
resources/timeseries.js: line 1008, col 36, Expected an assignment or function call and instead saw an expression.

resources/stuquery.js: line 16, col 35, The array literal notation [] is preferable.
resources/stuquery.js: line 59, col 31, The array literal notation [] is preferable.
resources/stuquery.js: line 67, col 37, The array literal notation [] is preferable.
resources/stuquery.js: line 76, col 119, Expected an assignment or function call and instead saw an expression.
resources/stuquery.js: line 130, col 61, The array literal notation [] is preferable.
resources/stuquery.js: line 183, col 21, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (getEvent, event, data, _obj)
resources/stuquery.js: line 292, col 21, Creating global 'for' variable. Should be 'for (var key ...'.
resources/stuquery.js: line 295, col 21, Creating global 'for' variable. Should be 'for (var key ...'.
resources/stuquery.js: line 323, col 21, 'i' is already defined.
resources/stuquery.js: line 329, col 31, The array literal notation [] is preferable.
resources/stuquery.js: line 457, col 44, Unnecessary semicolon.
resources/stuquery.js: line 473, col 112, 'rsp' used out of scope.

resources/graph.js: line 60, col 91, Unnecessary semicolon.
resources/graph.js: line 218, col 13, Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.
resources/graph.js: line 219, col 13, Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.
resources/graph.js: line 220, col 13, Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.
resources/graph.js: line 292, col 17, '_obj' is already defined.
resources/graph.js: line 493, col 67, 'd' used out of scope.
resources/graph.js: line 611, col 21, 'r' is already defined.
resources/graph.js: line 661, col 43, 'd' used out of scope.
resources/graph.js: line 759, col 25, 'i' is already defined.
resources/graph.js: line 803, col 17, 'i' is already defined.
resources/graph.js: line 932, col 17, 'c' is already defined.
resources/graph.js: line 977, col 45, 'x' used out of scope.
resources/graph.js: line 977, col 47, 'y' used out of scope.
resources/graph.js: line 1202, col 37, The array literal notation [] is preferable.
resources/graph.js: line 1308, col 21, 'i' is already defined.
resources/graph.js: line 1373, col 34, The array literal notation [] is preferable.
resources/graph.js: line 1413, col 39, 'v' is already defined.
resources/graph.js: line 1594, col 13, 'mn' is already defined.
resources/graph.js: line 1594, col 16, 'mx' is already defined.
resources/graph.js: line 1594, col 19, 'maxw' is already defined.
resources/graph.js: line 1677, col 86, Duplicate key 'ticks'.
resources/graph.js: line 1785, col 37, 'k' is already defined.
resources/graph.js: line 1789, col 41, 'k' is already defined.
resources/graph.js: line 1795, col 29, 'str' used out of scope.
resources/graph.js: line 1796, col 42, 'str' used out of scope.
resources/graph.js: line 1835, col 29, 'j' is already defined.
resources/graph.js: line 1958, col 80, 'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6').
resources/graph.js: line 2128, col 26, The array literal notation [] is preferable.
resources/graph.js: line 2135, col 51, The array literal notation [] is preferable.
resources/graph.js: line 2247, col 31, 'x1' is already defined.
resources/graph.js: line 2247, col 34, 'y1' is already defined.
resources/graph.js: line 2360, col 30, 't' is already defined.

73 errors
Exited with code 2
```

It might be worth checking which of these are potentially problematic vs can be ignored.

**Comment by slowe** [comment]
I should have fixed the "Unexpected ')'" issue on the main branch.

**Comment by astrofrog** [comment]
@slowe - indeed it is fixed, thanks! Just for the record, here are the warnings still raised by the ``jshint`` script - I'll see if any of the non-critical ones can be silenced:

```
resources/timeseries.js: line 136, col 44, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (_obj, checkAndGo, files)
resources/timeseries.js: line 599, col 59, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (updateProperties)
resources/timeseries.js: line 600, col 61, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (updateProperties)
resources/timeseries.js: line 601, col 59, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (updateProperties)
resources/timeseries.js: line 652, col 61, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (g, i, j)
resources/timeseries.js: line 843, col 52, Expected a conditional expression and instead saw an assignment.
resources/timeseries.js: line 941, col 16, eval can be harmful.

resources/stuquery.js: line 16, col 35, The array literal notation [] is preferable.
resources/stuquery.js: line 59, col 31, The array literal notation [] is preferable.
resources/stuquery.js: line 67, col 37, The array literal notation [] is preferable.
resources/stuquery.js: line 76, col 119, Expected an assignment or function call and instead saw an expression.
resources/stuquery.js: line 130, col 61, The array literal notation [] is preferable.
resources/stuquery.js: line 183, col 21, Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (getEvent, event, data, _obj)
resources/stuquery.js: line 292, col 21, Creating global 'for' variable. Should be 'for (var key ...'.
resources/stuquery.js: line 295, col 21, Creating global 'for' variable. Should be 'for (var key ...'.
resources/stuquery.js: line 323, col 21, 'i' is already defined.
resources/stuquery.js: line 329, col 31, The array literal notation [] is preferable.
resources/stuquery.js: line 457, col 44, Unnecessary semicolon.
resources/stuquery.js: line 473, col 112, 'rsp' used out of scope.

resources/graph.js: line 60, col 91, Unnecessary semicolon.
resources/graph.js: line 218, col 13, Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.
resources/graph.js: line 219, col 13, Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.
resources/graph.js: line 220, col 13, Function declarations should not be placed in blocks. Use a function expression or move the statement to the top of the outer function.
resources/graph.js: line 292, col 17, '_obj' is already defined.
resources/graph.js: line 493, col 67, 'd' used out of scope.
resources/graph.js: line 611, col 21, 'r' is already defined.
resources/graph.js: line 661, col 43, 'd' used out of scope.
resources/graph.js: line 759, col 25, 'i' is already defined.
resources/graph.js: line 803, col 17, 'i' is already defined.
resources/graph.js: line 945, col 17, 'c' is already defined.
resources/graph.js: line 990, col 45, 'x' used out of scope.
resources/graph.js: line 990, col 47, 'y' used out of scope.
resources/graph.js: line 1215, col 37, The array literal notation [] is preferable.
resources/graph.js: line 1321, col 21, 'i' is already defined.
resources/graph.js: line 1386, col 34, The array literal notation [] is preferable.
resources/graph.js: line 1426, col 39, 'v' is already defined.
resources/graph.js: line 1607, col 13, 'mn' is already defined.
resources/graph.js: line 1607, col 16, 'mx' is already defined.
resources/graph.js: line 1607, col 19, 'maxw' is already defined.
resources/graph.js: line 1690, col 86, Duplicate key 'ticks'.
resources/graph.js: line 1798, col 37, 'k' is already defined.
resources/graph.js: line 1802, col 41, 'k' is already defined.
resources/graph.js: line 1808, col 29, 'str' used out of scope.
resources/graph.js: line 1809, col 42, 'str' used out of scope.
resources/graph.js: line 1848, col 29, 'j' is already defined.
resources/graph.js: line 1971, col 80, 'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6').
resources/graph.js: line 2141, col 26, The array literal notation [] is preferable.
resources/graph.js: line 2148, col 51, The array literal notation [] is preferable.
resources/graph.js: line 2260, col 31, 'x1' is already defined.
resources/graph.js: line 2260, col 34, 'y1' is already defined.
resources/graph.js: line 2373, col 30, 't' is already defined.
```

**Comment by slowe** [comment]
I've fixed quite a few more. There are still some warnings left.

**Pull request merged**
